### ISSUE TITLE
implement place path card test and logic 3

### ISSUE THREAD

**Issue by kayac-chang** [Game-as-a-Service/saboteur-remix#27]
```
given:
  a board with
    - a start card at position (0, 0)
    - a path card [deadend top left right] at position (0, -1)
when:
  place
    path card [deadend left right] at position (1, -1)
then:
  the path card cannot be placed.
```

**Comment by Tuhacrt** [comment]
Hello, I met some problems while implement this test.
I also pushed my implement branch, so you can check it clearly: 
[test/place-path-card-test-logic-3](https://github.com/Game-as-a-Service/saboteur-remix/tree/test/place-path-card-test-logic-3)

1. The path card [deadend left right] **Can be placed at (1, -1)**. 
    The description of this test or the way I place cards might be wrong?
2. How should I check the event source correctly? 
Currently I assume the path card [deadend left right] can be placed is **Right**.
So the test description would be like this:
```
given:
      a board with
        - a start card at position (0, 0)
        - a path card [deadend top left right] at position (0, -1)
    when:
      place
        path card [deadend left right] at position (1, -1)
    then:
      - should return
        - path card has been placed event with
          - deadend left right card at position (1, -1)
      - event source should includes
        - path card has been placed event with
          - start card at position (0, 0)
          - path card [deadend top left right] at position (0, -1)
        - and path card has been placed event with
          - path card [deadend left right] at position (1, -1)
```
Is there any problem about the check of event source part?
